services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  test:
    build: ./backend
    command: poetry run pytest
    volumes:
      - ./backend:/app
    profiles:
      - test