services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  test:
    build: ./backend
    command: poetry run pytest
    volumes:
      - ./backend:/app
    profiles:
      - test