name: Heroku Deployment

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "lib-mgmt-dl-ezo"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          team: "dartslive"
          
      - name: Set Heroku stack to heroku-22
        run: |
          heroku stack:set heroku-22 -a lib-mgmt-dl-ezo
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Deploy to Heroku
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/lib-mgmt-dl-ezo.git HEAD:main --force
